import { Product, Banner } from "@/types";

export const FEATURED_BANNERS: Banner[] = [
  {
    id: "banner-1",
    type: "Homepage Banner",
    title: "Handcrafted Eternal Botanicals",
    subtitle: "Preserving Nature's Timeless Grace in Premium Optical Resin & 24K Gold",
    ctaText: "Explore Luxury Collection",
    ctaLink: "#collections",
    desktopImageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1920&q=85",
    mobileImageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85",
    isActive: true,
    priority: 1,
  },
  {
    id: "banner-2",
    type: "Festival Banner",
    title: "Bespoke Bridal Bouquet Keepsakes",
    subtitle: "Turn Your Wedding Flowers into Heirlooms That Last Forever",
    ctaText: "Book Preservation",
    ctaLink: "#preservation",
    desktopImageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1920&q=85",
    isActive: true,
    priority: 2,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    slug: "royal-emerald-pressed-fern-necklace",
    name: "Royal Emerald Fern Pendant",
    tagline: "Real Forest Fern encased in UV-Resistant Crystal Resin with 24K Gold Flakes",
    description: "Handcrafted luxury pendant carrying a real, hand-harvested forest fern leaf captured in high-transparency crystal resin, accented with genuine 24K gold foil flakes and suspended on an 18k gold-plated snake chain.",
    category: "Pendant",
    collections: ["Luxury Collection", "Trending", "Best Sellers"],
    basePriceINR: 2999,
    compareAtPriceINR: 3999,
    rating: 4.9,
    reviewCount: 48,
    isCustomizable: true,
    isFeatured: true,
    isBestSeller: true,
    flowerDetails: "Hand-picked Himalayan Forest Fern & Gold Leaf",
    resinType: "UV-Stabilized Optical Grade Crystal Epoxy",
    materials: ["24K Gold Flakes", "Sterling Silver Base", "Real Botanical Leaf"],
    careGuide: [
      "Keep away from direct prolonged heat exposure.",
      "Clean softly with a micro-fiber cloth.",
      "Store in the provided velvet luxury box.",
    ],
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
    ],
    variants: [
      {
        id: "var-1-1",
        productId: "prod-1",
        sku: "BOT-PEND-001-AU",
        title: "18K Gold Plated / 18 inch Chain",
        priceINR: 2999,
        compareAtPriceINR: 3999,
        inventoryQuantity: 15,
        metalColor: "Gold",
        size: "18 inch",
        shape: "Oval Drop",
        weightGrams: 12,
        dimensionsCm: "3.5 x 2.2 cm",
        images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85"],
      },
      {
        id: "var-1-2",
        productId: "prod-1",
        sku: "BOT-PEND-001-AG",
        title: "925 Sterling Silver / 18 inch Chain",
        priceINR: 2799,
        inventoryQuantity: 10,
        metalColor: "Silver",
        size: "18 inch",
        shape: "Oval Drop",
        weightGrams: 12,
        dimensionsCm: "3.5 x 2.2 cm",
        images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85"],
      },
    ],
  },
  {
    id: "prod-2",
    slug: "blushing-rose-petal-gold-earrings",
    name: "Blushing Rose Drop Earrings",
    tagline: "Preserved Miniature Wild Rose Petals with Pearl Accents",
    description: "Pair of ethereal drop earrings holding preserved crimson rose petals encased in glass-smooth resin spheres with rose gold elements.",
    category: "Drop Earrings",
    collections: ["Wedding Collection", "New Arrivals"],
    basePriceINR: 1899,
    compareAtPriceINR: 2499,
    rating: 4.8,
    reviewCount: 32,
    isCustomizable: true,
    isFeatured: true,
    isNewArrival: true,
    flowerDetails: "Miniature Kashmiri Damask Rose Petals",
    resinType: "Ultra-Clear Jewelry Grade Resin",
    materials: ["Rose Gold Plated Hooks", "Freshwater Pearls", "Botanical Petals"],
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=85",
    ],
    variants: [
      {
        id: "var-2-1",
        productId: "prod-2",
        sku: "BOT-EAR-002-RG",
        title: "Rose Gold Drop",
        priceINR: 1899,
        inventoryQuantity: 20,
        metalColor: "Rose Gold",
        images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85"],
      },
    ],
  },
  {
    id: "prod-3",
    slug: "custom-initial-pressed-flower-bookmark",
    name: "Golden Botanical Letter Bookmark",
    tagline: "Personalized Resin Letter with Dried Hydrangeas & Gold Foil",
    description: "Handcrafted resin initial bookmark featuring real pressed hydrangeas, gold flakes, and a luxury silk tassel.",
    category: "Bookmarks",
    collections: ["Personalized Gifts", "Best Sellers"],
    basePriceINR: 799,
    compareAtPriceINR: 999,
    rating: 5.0,
    reviewCount: 94,
    isCustomizable: true,
    isBestSeller: true,
    flowerDetails: "Pressed Blue & Pink Hydrangeas",
    resinType: "High Gloss Resin",
    materials: ["Gold Foil", "Silk Tassel", "Pressed Flowers"],
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=85",
    ],
    variants: [
      {
        id: "var-3-1",
        productId: "prod-3",
        sku: "BOT-BM-003",
        title: "Custom Initial (A-Z)",
        priceINR: 799,
        inventoryQuantity: 50,
        images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=85"],
      },
    ],
  },
  {
    id: "prod-4",
    slug: "luxury-botanical-resin-coasters-set",
    name: "Oceanic Botanical Coasters (Set of 4)",
    tagline: "Hexagonal Gold-Rimed Coasters with Dried Floral Inlays",
    description: "Set of 4 heavy resin coasters with gold painted edges, filled with pressed wildflowers and metallic foil for a luxurious living room centerpiece.",
    category: "Coasters",
    collections: ["Luxury Collection"],
    basePriceINR: 2499,
    compareAtPriceINR: 3299,
    rating: 4.9,
    reviewCount: 27,
    isCustomizable: true,
    isFeatured: true,
    flowerDetails: "Wild Chamomile, Lavender & Baby's Breath",
    resinType: "Heat Resistant Tabletop Resin (up to 90°C)",
    materials: ["24K Metallic Paint Edge", "Pressed Wildflowers"],
    images: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=85",
    ],
    variants: [
      {
        id: "var-4-1",
        productId: "prod-4",
        sku: "BOT-COAST-004",
        title: "Set of 4 / Hexagonal",
        priceINR: 2499,
        inventoryQuantity: 8,
        images: ["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=85"],
      },
    ],
  },
];
